// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Register.BlazorApp.Data;

#nullable disable

namespace Register.BlazorApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Register.BlazorApp.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Register.Shared.Domain.ActivityLog", b =>
                {
                    b.Property<int>("ActivityLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityLogId"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("PerformedActivityDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ActivityLogId");

                    b.ToTable("ActivityLogs");

                    b.HasData(
                        new
                        {
                            ActivityLogId = 1,
                            EndTime = new DateTime(2024, 11, 29, 11, 10, 31, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  1",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 7, 31, 17, 40, 44, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 2,
                            EndTime = new DateTime(2024, 2, 3, 15, 0, 49, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  2",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 1, 28, 14, 27, 55, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 3,
                            EndTime = new DateTime(2024, 7, 28, 0, 9, 34, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  3",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 7, 22, 11, 17, 32, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 4,
                            EndTime = new DateTime(2024, 7, 27, 7, 9, 57, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  4",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 4, 19, 21, 44, 43, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 5,
                            EndTime = new DateTime(2024, 8, 31, 16, 45, 24, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  5",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 3, 6, 7, 21, 55, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 6,
                            EndTime = new DateTime(2024, 12, 28, 3, 30, 18, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  6",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 8, 21, 23, 30, 59, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 7,
                            EndTime = new DateTime(2024, 7, 29, 20, 58, 18, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  7",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 4, 29, 20, 32, 19, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 8,
                            EndTime = new DateTime(2024, 1, 19, 20, 27, 16, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  8",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 11, 3, 10, 25, 13, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 9,
                            EndTime = new DateTime(2024, 10, 11, 18, 24, 31, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  9",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 7, 21, 2, 53, 53, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 10,
                            EndTime = new DateTime(2024, 6, 3, 9, 43, 49, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  10",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 4, 13, 9, 44, 10, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 11,
                            EndTime = new DateTime(2024, 12, 25, 17, 57, 31, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  11",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 1, 23, 11, 7, 2, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 12,
                            EndTime = new DateTime(2024, 6, 4, 20, 51, 1, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  12",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 8, 24, 10, 38, 3, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 13,
                            EndTime = new DateTime(2024, 1, 28, 6, 23, 6, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  13",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 12, 14, 2, 48, 42, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 14,
                            EndTime = new DateTime(2024, 8, 24, 13, 28, 59, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  14",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 7, 6, 3, 24, 5, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 15,
                            EndTime = new DateTime(2024, 10, 22, 1, 46, 53, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  15",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 12, 25, 4, 2, 48, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 16,
                            EndTime = new DateTime(2024, 6, 14, 12, 22, 34, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  16",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 9, 22, 21, 9, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 17,
                            EndTime = new DateTime(2024, 9, 20, 7, 14, 39, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  17",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 9, 26, 2, 24, 7, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 18,
                            EndTime = new DateTime(2024, 3, 23, 12, 16, 56, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  18",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 10, 28, 10, 57, 19, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 19,
                            EndTime = new DateTime(2024, 10, 31, 11, 37, 29, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  19",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 8, 15, 21, 37, 20, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 20,
                            EndTime = new DateTime(2024, 4, 17, 19, 50, 30, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  20",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 8, 6, 9, 26, 31, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 21,
                            EndTime = new DateTime(2024, 2, 15, 18, 12, 52, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  21",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 7, 30, 4, 4, 27, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 22,
                            EndTime = new DateTime(2024, 4, 22, 23, 22, 58, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  22",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 5, 8, 23, 56, 37, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 23,
                            EndTime = new DateTime(2024, 10, 13, 7, 18, 17, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  23",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 4, 20, 17, 17, 50, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 24,
                            EndTime = new DateTime(2024, 5, 30, 17, 17, 50, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  24",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 12, 23, 10, 12, 50, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 25,
                            EndTime = new DateTime(2024, 2, 1, 5, 14, 40, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  25",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 12, 30, 1, 54, 5, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 26,
                            EndTime = new DateTime(2024, 9, 16, 4, 45, 23, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  26",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 11, 26, 0, 4, 3, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 27,
                            EndTime = new DateTime(2024, 7, 31, 17, 39, 4, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  27",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 5, 20, 6, 50, 15, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 28,
                            EndTime = new DateTime(2024, 2, 20, 17, 8, 14, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  28",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 6, 20, 21, 54, 6, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 29,
                            EndTime = new DateTime(2024, 2, 6, 12, 43, 18, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  29",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 1, 8, 14, 51, 53, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 30,
                            EndTime = new DateTime(2024, 9, 18, 17, 5, 59, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  30",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 4, 13, 23, 47, 33, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 31,
                            EndTime = new DateTime(2024, 1, 12, 14, 19, 59, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  31",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 9, 18, 13, 14, 45, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 32,
                            EndTime = new DateTime(2024, 3, 25, 12, 58, 51, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  32",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 1, 31, 23, 40, 48, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 33,
                            EndTime = new DateTime(2024, 8, 10, 7, 23, 11, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  33",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 11, 15, 16, 19, 36, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 34,
                            EndTime = new DateTime(2024, 7, 24, 6, 48, 16, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  34",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 10, 31, 20, 26, 17, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 35,
                            EndTime = new DateTime(2024, 3, 8, 14, 33, 44, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  35",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 6, 26, 1, 49, 53, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 36,
                            EndTime = new DateTime(2024, 2, 16, 15, 59, 51, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  36",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 8, 17, 3, 56, 5, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 37,
                            EndTime = new DateTime(2024, 4, 3, 14, 56, 31, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  37",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 6, 20, 20, 15, 16, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 38,
                            EndTime = new DateTime(2024, 7, 7, 11, 5, 23, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  38",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 5, 15, 17, 49, 31, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 39,
                            EndTime = new DateTime(2024, 5, 13, 5, 28, 2, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  39",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 8, 1, 21, 52, 20, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 40,
                            EndTime = new DateTime(2024, 6, 1, 1, 28, 58, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  40",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 12, 2, 2, 31, 31, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 41,
                            EndTime = new DateTime(2024, 3, 12, 0, 38, 30, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  41",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 5, 11, 17, 54, 29, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 42,
                            EndTime = new DateTime(2024, 1, 10, 7, 12, 23, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  42",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 3, 18, 3, 9, 8, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 43,
                            EndTime = new DateTime(2024, 4, 5, 18, 43, 41, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  43",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 12, 1, 19, 35, 51, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 44,
                            EndTime = new DateTime(2024, 8, 14, 11, 9, 16, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  44",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 8, 30, 6, 3, 41, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 45,
                            EndTime = new DateTime(2024, 6, 6, 21, 13, 18, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  45",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 1, 13, 2, 46, 50, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 46,
                            EndTime = new DateTime(2024, 9, 24, 18, 26, 20, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  46",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 8, 15, 21, 10, 52, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 47,
                            EndTime = new DateTime(2024, 11, 29, 18, 16, 35, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  47",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 8, 27, 10, 33, 38, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 48,
                            EndTime = new DateTime(2024, 11, 23, 2, 21, 47, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  48",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 9, 30, 18, 7, 31, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 49,
                            EndTime = new DateTime(2024, 8, 14, 21, 30, 20, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  49",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 10, 27, 12, 21, 9, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 50,
                            EndTime = new DateTime(2024, 6, 6, 9, 47, 50, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  50",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 8, 18, 6, 2, 12, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 51,
                            EndTime = new DateTime(2024, 12, 5, 22, 10, 48, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  51",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 12, 26, 19, 25, 45, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 52,
                            EndTime = new DateTime(2024, 5, 18, 2, 43, 42, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  52",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 8, 9, 20, 28, 14, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 53,
                            EndTime = new DateTime(2024, 8, 4, 19, 12, 45, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  53",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 3, 4, 8, 39, 58, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 54,
                            EndTime = new DateTime(2024, 6, 30, 7, 16, 14, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  54",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 10, 5, 2, 0, 59, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 55,
                            EndTime = new DateTime(2024, 8, 31, 20, 23, 52, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  55",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 9, 10, 10, 14, 9, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 56,
                            EndTime = new DateTime(2024, 3, 23, 7, 30, 15, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  56",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 5, 29, 23, 56, 10, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 57,
                            EndTime = new DateTime(2024, 4, 9, 18, 34, 24, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  57",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 12, 21, 11, 28, 55, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 58,
                            EndTime = new DateTime(2024, 3, 12, 4, 55, 21, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  58",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 7, 5, 18, 45, 18, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 59,
                            EndTime = new DateTime(2024, 7, 9, 5, 59, 7, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  59",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 9, 13, 2, 53, 42, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 60,
                            EndTime = new DateTime(2024, 1, 24, 12, 25, 52, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  60",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 8, 12, 4, 27, 59, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 61,
                            EndTime = new DateTime(2024, 1, 23, 14, 51, 35, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  61",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 2, 7, 17, 20, 28, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 62,
                            EndTime = new DateTime(2024, 11, 26, 2, 22, 38, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  62",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 11, 29, 3, 44, 25, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 63,
                            EndTime = new DateTime(2024, 4, 9, 18, 1, 53, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  63",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 6, 6, 7, 55, 5, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 64,
                            EndTime = new DateTime(2024, 9, 24, 21, 47, 32, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  64",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 12, 3, 12, 47, 55, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 65,
                            EndTime = new DateTime(2024, 6, 24, 4, 20, 20, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  65",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 8, 16, 23, 38, 40, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 66,
                            EndTime = new DateTime(2024, 7, 21, 22, 26, 41, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  66",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 7, 28, 11, 45, 32, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 67,
                            EndTime = new DateTime(2024, 4, 26, 23, 40, 28, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  67",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 12, 4, 4, 6, 20, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 68,
                            EndTime = new DateTime(2024, 12, 15, 6, 42, 21, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  68",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 8, 21, 19, 8, 47, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 69,
                            EndTime = new DateTime(2024, 10, 27, 20, 10, 21, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  69",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 5, 9, 14, 38, 17, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 70,
                            EndTime = new DateTime(2024, 11, 15, 0, 35, 37, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  70",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 10, 11, 20, 10, 52, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 71,
                            EndTime = new DateTime(2024, 6, 7, 8, 33, 9, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  71",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 12, 29, 16, 17, 55, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 72,
                            EndTime = new DateTime(2024, 11, 22, 4, 34, 21, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  72",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 5, 17, 12, 12, 29, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 73,
                            EndTime = new DateTime(2024, 4, 2, 12, 1, 53, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  73",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 7, 29, 20, 32, 49, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 74,
                            EndTime = new DateTime(2024, 11, 29, 10, 18, 2, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  74",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 8, 28, 8, 36, 10, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 75,
                            EndTime = new DateTime(2024, 3, 20, 23, 16, 5, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  75",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 10, 13, 17, 18, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 76,
                            EndTime = new DateTime(2024, 7, 19, 5, 9, 14, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  76",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 6, 21, 21, 23, 51, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 77,
                            EndTime = new DateTime(2024, 2, 25, 17, 14, 13, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  77",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 9, 25, 11, 41, 56, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 78,
                            EndTime = new DateTime(2024, 9, 21, 6, 50, 5, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  78",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 12, 19, 20, 59, 39, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 79,
                            EndTime = new DateTime(2024, 6, 27, 11, 59, 7, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  79",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 2, 20, 2, 31, 28, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 80,
                            EndTime = new DateTime(2024, 10, 3, 8, 41, 43, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  80",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 5, 8, 17, 28, 47, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 81,
                            EndTime = new DateTime(2024, 5, 29, 11, 6, 58, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  81",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 11, 16, 12, 51, 23, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 82,
                            EndTime = new DateTime(2024, 5, 30, 23, 13, 49, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  82",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 9, 25, 14, 26, 6, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 83,
                            EndTime = new DateTime(2024, 12, 6, 19, 23, 18, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  83",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 9, 29, 18, 3, 17, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 84,
                            EndTime = new DateTime(2024, 5, 18, 6, 15, 21, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  84",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 9, 23, 2, 13, 56, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 85,
                            EndTime = new DateTime(2024, 11, 15, 20, 39, 24, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  85",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 7, 20, 15, 3, 45, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 86,
                            EndTime = new DateTime(2024, 8, 23, 3, 18, 26, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  86",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 12, 18, 11, 38, 44, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 87,
                            EndTime = new DateTime(2024, 3, 16, 20, 39, 4, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  87",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 6, 28, 3, 51, 16, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 88,
                            EndTime = new DateTime(2024, 11, 20, 17, 46, 19, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  88",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 4, 6, 5, 17, 41, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 89,
                            EndTime = new DateTime(2024, 3, 3, 20, 16, 55, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  89",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 6, 13, 13, 24, 19, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 90,
                            EndTime = new DateTime(2024, 1, 22, 13, 18, 12, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  90",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 7, 12, 21, 47, 35, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 91,
                            EndTime = new DateTime(2024, 12, 19, 3, 44, 15, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  91",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 1, 10, 15, 3, 44, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 92,
                            EndTime = new DateTime(2024, 4, 12, 17, 13, 5, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  92",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 1, 9, 15, 49, 55, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 93,
                            EndTime = new DateTime(2024, 10, 7, 12, 45, 17, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  93",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 6, 26, 13, 28, 8, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 94,
                            EndTime = new DateTime(2024, 2, 3, 2, 24, 43, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  94",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 9, 12, 13, 31, 36, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 95,
                            EndTime = new DateTime(2024, 6, 21, 23, 54, 32, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  95",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 8, 31, 17, 48, 11, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 96,
                            EndTime = new DateTime(2024, 12, 3, 6, 23, 3, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  96",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 12, 3, 17, 39, 17, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 97,
                            EndTime = new DateTime(2024, 11, 7, 18, 45, 14, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  97",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 5, 17, 0, 17, 47, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 98,
                            EndTime = new DateTime(2024, 12, 22, 12, 30, 5, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  98",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 4, 20, 14, 20, 52, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ActivityLogId = 99,
                            EndTime = new DateTime(2024, 10, 24, 22, 18, 54, 0, DateTimeKind.Unspecified),
                            PerformedActivityDescription = "Activity  99",
                            PersonId = 1,
                            StartTime = new DateTime(2024, 6, 11, 9, 16, 37, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Register.Shared.Domain.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryId = 1,
                            Name = "Sweden"
                        },
                        new
                        {
                            CountryId = 2,
                            Name = "Germany"
                        },
                        new
                        {
                            CountryId = 3,
                            Name = "Netherlands"
                        },
                        new
                        {
                            CountryId = 4,
                            Name = "Denmark"
                        },
                        new
                        {
                            CountryId = 5,
                            Name = "Finland"
                        },
                        new
                        {
                            CountryId = 6,
                            Name = "Island"
                        },
                        new
                        {
                            CountryId = 7,
                            Name = "UK"
                        },
                        new
                        {
                            CountryId = 8,
                            Name = "France"
                        },
                        new
                        {
                            CountryId = 9,
                            Name = "Norway"
                        },
                        new
                        {
                            CountryId = 10,
                            Name = "Belgium"
                        });
                });

            modelBuilder.Entity("Register.Shared.Domain.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonId"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExitDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOnHoliday")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("JoinedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<int?>("MaritalStatus")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoleCategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("Smoker")
                        .HasColumnType("bit");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zip")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonId");

                    b.HasIndex("CountryId");

                    b.HasIndex("RoleCategoryId");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            PersonId = 1,
                            BirthDate = new DateTime(1995, 8, 12, 12, 16, 10, 44, DateTimeKind.Unspecified).AddTicks(1539),
                            City = "Stockholm",
                            Comment = "Generated registration on model creating",
                            CountryId = 1,
                            Email = "generated.person@registered.test",
                            FirstName = "Anna",
                            Gender = 1,
                            IsOnHoliday = false,
                            JoinedDate = new DateTime(2015, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Anderson",
                            Latitude = 59.333219999999997,
                            Longitude = 18.064879999999999,
                            MaritalStatus = 0,
                            PhoneNumber = "070000000",
                            RoleCategoryId = 1,
                            Smoker = false,
                            Street = "Sveavägen 1",
                            Zip = "11157"
                        });
                });

            modelBuilder.Entity("Register.Shared.Domain.RoleCategory", b =>
                {
                    b.Property<int>("RoleCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleCategoryId"));

                    b.Property<string>("RoleCategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleCategoryId");

                    b.ToTable("RoleCategories");

                    b.HasData(
                        new
                        {
                            RoleCategoryId = 1,
                            RoleCategoryName = "Management"
                        },
                        new
                        {
                            RoleCategoryId = 2,
                            RoleCategoryName = "Administration"
                        },
                        new
                        {
                            RoleCategoryId = 3,
                            RoleCategoryName = "Finance"
                        },
                        new
                        {
                            RoleCategoryId = 4,
                            RoleCategoryName = "IT"
                        },
                        new
                        {
                            RoleCategoryId = 5,
                            RoleCategoryName = "Consulting"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Register.BlazorApp.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Register.BlazorApp.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Register.BlazorApp.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Register.BlazorApp.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Register.Shared.Domain.Person", b =>
                {
                    b.HasOne("Register.Shared.Domain.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");

                    b.HasOne("Register.Shared.Domain.RoleCategory", "RoleCategory")
                        .WithMany()
                        .HasForeignKey("RoleCategoryId");

                    b.Navigation("Country");

                    b.Navigation("RoleCategory");
                });
#pragma warning restore 612, 618
        }
    }
}
